import Head from "next/head";
import { Footer } from "../components/layout/Footer";
import { Links } from "../components/Links";

const Home = () => {
  return (
    <div
      className="min-h-screen py-12
                text-xl font-mono text-gray-100 dark:text-gray-300
                bg-gradient-to-tr 
              from-pink-400 via-blue-300 to-green-200
              dark:from-indigo-700 dark:via-purple-600 dark:to-pink-500"
    >
      <Head>
        <title>Link App 2.1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="flex justify-center mb-5 font-bold">
          Welcome to Ken&apos;s links
        </h1>
        <Links />
      </main>
      <Footer />
    </div>
  );
};
export default Home;
