import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Footer } from "../components/layout/Footer";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Link App 2.1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>Link App 2.1 and more</main>
      <Footer />
    </div>
  );
};
export default Home;
